# RLbench dataset path
dataset_root: /tmp/

# path to save rendered datasets
save_path: null

# directory for random textures
textures_path: './textures'

# Cameras to use and sphere scaling
cameras: ['wrist', 'front', 'right_shoulder', 'left_shoulder', 'overhead']
camera_scales: [3.0, 8.0, 6.5, 6.5, 6.5]


# RLBench task
task: 'take_lid_off_saucepan'

# number of episodes
episodes: 100

# number of episodes to start from
episode_offset: 0

# variation index
variation: 0

# number of parallel processes to use
num_processes: 1

# image dimensions
image_width: 256
image_height: 256

# distance to near clipping plane for intrinsic camera
znear: 0.00001

# distance to the far clipping plane for intrinsic camera
zfar: 3.0

# which action in the future to render spheres
action_horizon: 20

# alpha blend between original image and random texture
alpha_blend: 0.7

# render configuration
render:
  sphere:
    # sphere radius
    radius: 0.01
  # which joints to render for each camera
  joints:
    wrist: [1, 3, 5]
    front: [1, 3, 5]
    right_shoulder: [1, 3, 5]
    left_shoulder: [1, 3, 5]
    overhead: []

# what type of actions to generate
draw:
  # full Context
  rgb_rendered: True
  # random Context
  rnd_bg: True
